### ISSUE TITLE
Can't install w/ composer

### ISSUE THREAD

**Issue by drdogbot7** [iamntz/carbon-fields-urlpicker#1]
I think there needs to be a tagged release?

> Problem 1
>     - The requested package iamntz/carbon-fields-urlpicker could not be found in any version, there may be a typo in the package name.

**Comment by iamntz** [comment]
Thanks! Actually was a typo in the readme, the correct path is `iamntz/carbon-fields-urlpicker` :)

**Comment by drdogbot7** [comment]
Still getting an error with composer

`  [InvalidArgumentException]
  Could not find package iamntz/carbon-fields-urlpicker at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability`

**Comment by iamntz** [comment]
Please make sure you have `"minimum-stability": "dev"` set in `composer.json`.
