### ISSUE TITLE
[Feature] - Associate the field to page/post ID

### ISSUE THREAD

**Issue by ESirop** [iamntz/carbon-fields-urlpicker#10]
Hi there,

First of all, I just want to say thanks for this nice addition to CF.

Anyway, I'm just having a little issue when updating a slug, and I thought it would be a nice feature :
When searching for a page/post, it could be nice to associate the field to the post by its ID.
That way, instead of just getting the URL as a plain text at this specific moment, we could retrieve the post URL by its ID.
So if we update a post slugs, we don't break the link.

I made a little graphic example just to show what I have in mind :

![feature](https://user-images.githubusercontent.com/3872849/84492933-3a8c2380-aca7-11ea-8fcf-ce9d7bf99ffd.jpg)

What do you think about that?

Regards,

**Comment by iamntz** [comment]
That's a great idea! However, the URL picker is the WP default picker, which provides little to no customizations :/
