### ISSUE TITLE
v3.x-dev conflict with Wordpress v5.6.2, Sage theme v9.0.10

### ISSUE THREAD

**Issue by vincenzobologna** [iamntz/carbon-fields-urlpicker#11]
Hello,

after installing v3.x-dev version had this error:

`Fatal error: Uncaught Error: Call to undefined function add_action() in [...]/vendor/iamntz/carbon-fields-urlpicker/field.php:7
Stack trace:
#0 [...]/vendor/composer/autoload_real.php(71): require()
#1 [...]/vendor/composer/autoload_real.php(61): composerRequire511ba04db4f2f6968fdac33800344033('c36202a7ae4f6da...', '[...]...')
#2 [...]/vendor/autoload.php(7): ComposerAutoloaderInit511ba04db4f2f6968fdac33800344033::getLoader()
#3 [...]/vendor/kylekatarnls/update-helper/src/UpdateHelper/UpdateHelper.php(143): include_once('...')
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code(45): UpdateHelper\UpdateHelper::check(Object(Composer\Script\Event))
#5 [internal function]: UpdateHelper\ComposerPlugin_composer_tmp0->onAut in [...]/vendor/iamntz/carbon-fields-urlpicker/field.php on line 7`

to resole i had to make a workaround wrapping add_action in a if(function_exists('add_action')){ ... } in order to make it work.
Can you verify that?

thanks.

**Comment by iamntz** [comment]
Hey @vincenzobologna can you give me more details about your set up?

It's inside your theme or installed as a plugin? Can you try to install it as `composer require iamntz/carbon-fields-urlpicker:v3.0.0` ?

**Comment by vincenzobologna** [comment]
Thanks for reply.

Here's my composer.json of theme (Sage v9.0.10, Wordpress v5.6.2):

`{
  "name": "roots/sage",
  "type": "wordpress-theme",
  "license": "MIT",
  "description": "WordPress starter theme with a modern development workflow",
  "homepage": "https://roots.io/sage/",
  "authors": [
    {
      "name": "Ben Word",
      "email": "ben@benword.com",
      "homepage": "https://github.com/retlehs"
    },
    {
      "name": "Scott Walkinshaw",
      "email": "scott.walkinshaw@gmail.com",
      "homepage": "https://github.com/swalkinshaw"
    },
    {
      "name": "QWp6t",
      "email": "hi@qwp6t.me",
      "homepage": "https://github.com/qwp6t"
    }
  ],
  "keywords": ["wordpress"],
  "support": {
    "issues": "https://github.com/roots/sage/issues",
    "forum": "https://discourse.roots.io/"
  },
  "autoload": {
    "psr-4": {
      "App\\": "app/"
    }
  },
  "require": {
    "php": ">=7.1",
    "composer/installers": "~1.9",
    "illuminate/support": "5.6.*",
    "roots/sage-lib": "~9.0.9",
    "soberwp/controller": "~2.1.0",
    "htmlburger/carbon-fields": "^3.2",
    "iamntz/carbon-fields-urlpicker": "v3.0.0"
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "^2.8.0",
    "roots/sage-installer": "~1.6"
  },
  "scripts": {
    "test": ["phpcs"],
    "post-create-project-cmd": [
      "Roots\\Sage\\Installer\\ComposerScript::postCreateProject"
    ]
  }
}
`

I tried with v.3.0.0 of your package, but i got the same error log, just after launcing composer require:

`Fatal error: Uncaught Error: Call to undefined function add_action() in .../vendor/iamntz/carbon-fields-urlpicker/field.php:7
Stack trace:
#0 ...vendor/composer/autoload_real.php(71): require()
#1 .../vendor/composer/autoload_real.php(61): composerRequire511ba04db4f2f6968fdac33800344033('c36202a7ae4f6da...', '...')
#2 .../vendor/autoload.php(7): ComposerAutoloaderInit511ba04db4f2f6968fdac33800344033::getLoader()
#3 .../vendor/kylekatarnls/update-helper/src/UpdateHelper/UpdateHelper.php(143): include_once('...')
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code(45): UpdateHelper\UpdateHelper::check(Object(Composer\Script\Event))
#5 [internal function]: UpdateHelper\ComposerPlugin_composer_tmp0->onAut in ...vendor/iamntz/carbon-fields-urlpicker/field.php on line 7`

The code which generate this error is this:

`<?php
use Carbon_Fields\Carbon_Fields;
use Carbon_Field_UrlPicker\UrlPicker_Field;

define('Carbon_Field_UrlPicker\\DIR', __DIR__);

add_action('after_setup_theme', function () {
	Carbon_Fields::extend(UrlPicker_Field::class, function ($container) {
		return new UrlPicker_Field( $container['arguments']['type'], $container['arguments']['name'], $container['arguments']['label'] );
	});
}, 99);`

and i "workarounded" changing in this:

`<?php
use Carbon_Fields\Carbon_Fields;
use Carbon_Field_UrlPicker\UrlPicker_Field;

define('Carbon_Field_UrlPicker\\DIR', __DIR__);

if(function_exists('add_action'){
add_action('after_setup_theme', function () {
	Carbon_Fields::extend(UrlPicker_Field::class, function ($container) {
		return new UrlPicker_Field( $container['arguments']['type'], $container['arguments']['name'], $container['arguments']['label'] );
	});
}, 99);
}`

I suspect it isn't best way to resolve. Probably this one comes before wordpress init hook? I'm sure you knows better than me.
I hope this can help you to fix that.

**Comment by iamntz** [comment]
Unfortunately I'm not familiar with Sage, so it might something that conflicts with that theme, as `add_action` is already available by the time the theme is loaded (or even plugins).

**Comment by vincenzobologna** [comment]
Thank you for the fix!
best.
