### ISSUE TITLE
Page editor Broken in last two commits

### ISSUE THREAD

**Issue by drdogbot7** [iamntz/carbon-fields-urlpicker#3]
In the page editor I get this error in javascript console:

`Uncaught Error: Could not find the component for type "urlpicker".`

When I add a 'urlpicker' field to a container then that container won't load. Data that's already in the database loads fine.

Using Carbonfields 2.1.1, WP 4.9.1.

**Comment by iamntz** [comment]
Try to update to carbon fields `2.2.0-beta.3`, which is the latest.

I've noticed that `define('SCRIPT_DEBUG', true);` in wp-config.php will temporary fix that error.

**Comment by drdogbot7** [comment]
Latest commit (ca27271) working with carbon fields 2.2.0-beta.4. Thx.

**Comment by timiwahalahti** [comment]
I'm having this kind of problems as well.

`TypeError: e[r] is undefined`
`Error: Could not find the component for type "urlpicker".`

WP 4.9.4
CRB 2.2.0-beta.4

WP installation is using bedrock and CRB is loaded in theme.
