### ISSUE TITLE
Closing the insert/edit link popup without adding a link adds a blank text field

### ISSUE THREAD

**Issue by ttamnedlog** [iamntz/carbon-fields-urlpicker#4]
I'm not sure what all information would be helpful, but I'm happy to provide more if you need it.

WP 4.9.8
Carbon Fields 2.2
URLpicker commit 5150de5
Chrome 68.0.3440.106

If I click the Select Link button, but then click Cancel instead of adding a link, a blank text field appears. Repeating this causes additional text fields to appear. These fields appear right beneath the button. Prior to this current commit, this behavior still happened but it happened at the bottom of the browser window.

**Comment by iamntz** [comment]
Yup, that's enough, thanks.

Fixed on 69885a3
