### ISSUE TITLE
CarbonFields 3.0 Support

### ISSUE THREAD

**Issue by madmanlear** [iamntz/carbon-fields-urlpicker#6]
Doesn't appear to work in CarbonFields 3.0. I've tried with and without Gutenberg enabled.

The javascript error `Field urlpicker isn't registered.` is thrown.

**Comment by gonssal** [comment]
Sorry to comment in a closed issue, but I think it's better than opening a new one.

Why don't you just publish a 3.0 version in packagist instead of the 3.x-dev, so we can use "^3.0"?
