### ISSUE TITLE
Link is not saved (CF 3)

### ISSUE THREAD

**Issue by KevinSupertramp** [iamntz/carbon-fields-urlpicker#7]
Hi there,

Firstly, thank you for the plugin! I'm trying to use it with the latest version of Carbon Fields but the link is not saved nor selected after clicking on "Add Link".

Kind regards,

**Comment by iamntz** [comment]
Hey Kevin. Unfortunately I can't replicate your issue. Are you sure you're on the branch `v3` ?

**Comment by iamntz** [comment]
You can either update your `composer.json` file to read:

```
"require": {
  "iamntz/carbon-fields-urlpicker": "v3.x-dev"
}
```

Or install it via cli:

```
composer require iamntz/carbon-fields-urlpicker:v3.x-dev
```

**Comment by KevinSupertramp** [comment]
Hi @iamntz ,

Thanks for your quick reply and yes I am using the v3. The field is used in a Gutenberg block (CF_Block). I don't get any error in the console either.

I just tried in a "theme_options" container and it works. It looks like it might be related when it is used in a block container?

Best regards,

**Comment by iamntz** [comment]
Mmmm, I didn't used Carbon as a gutenberg block until now. I'll dig into it and I'll let you know :)

**Comment by KevinSupertramp** [comment]
@iamntz That's awesome, thanks so much!

**Comment by iamntz** [comment]
From what i can see, the data _is_ saved. Is just that... the button isn't updated. Well, I assume combining legacy with new is not always the best idea 🗡

```
  Block::make( 'ntz/urlpicker-test', __( 'URL Picker test' ) )
      ->add_fields( array(
          Field::make( 'urlpicker', 'urlpicker', __( 'Block URL' ) ),
      ) )
      ->set_render_callback( function ( $fields, $attributes = null, $inner_blocks = null ) {
          echo '<pre>';
              print_r( $fields );
              print_r( $attributes );
              print_r( $inner_blocks );
          echo '</pre>';
      } );
```

Will update in a bit.

**Comment by iamntz** [comment]
Unfortunately, it seems that there is an issue with WP core itself:

https://github.com/WordPress/gutenberg/issues/11432

So for now this will be no stand by.

**Comment by KevinSupertramp** [comment]
Hi, oh okay. I think they applied the fix in 5.1 though?

Anyway, I realised that the data is saved but the field id (key) is not used, instead it's the auto-generated CF I guess? Maybe this is why the data is not loaded?

![screen shot 2019-03-04 at 10 24 43](https://user-images.githubusercontent.com/1142786/53727307-cccc3780-3e67-11e9-9199-c60b17dc19d8.png)

**Comment by iamntz** [comment]
Ups, that was my mistake. Which is fixed now :)

**Comment by gaambo** [comment]
Hi there, I had a similar problem/bug - the value was saved but not shown/editable in the backend. Seems there was a bug how the value was accessed via the field props (or maybe carbon fields api changed). Made a pull request - just some minor changes, so should be good to go.
